# Generated by Django 5.0.2 on 2024-02-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trade_code',
            field=models.TextField(null=True),
        ),
    ]
