# Generated by Django 5.0.2 on 2024-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0002_alter_stock_trade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.TextField(null=True),
        ),
    ]
