# Generated by Django 5.0.2 on 2024-02-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0003_alter_stock_close_alter_stock_high_alter_stock_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trade_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.TextField(),
        ),
    ]
