# Generated by Django 5.0.2 on 2024-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0004_alter_stock_close_alter_stock_high_alter_stock_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
